Add required status check

diff --git a/.github/workflows/integration_test.yaml b/.github/workflows/integration_test.yaml
--- a/.github/workflows/integration_test.yaml
+++ b/.github/workflows/integration_test.yaml
@@ -6,7 +6,7 @@ on:
     - cron: "0 15 * * SAT"
 
 jobs:
-  integration-tests:
+  integration-test:
     uses: canonical/charm-ci/.github/workflows/integration-test.yml@main
     secrets: inherit
     permissions:
@@ -17,3 +17,20 @@ jobs:
       working-directory: .
       spread-jobs-include: "*tests/integration*"
       build-timeout-minutes: 120
+  required_status_checks:
+    name: Required Integration Test Status Checks
+    runs-on: ubuntu-latest
+    needs:
+      - integration-test
+    if: always() && !cancelled()
+    timeout-minutes: 5
+    steps:
+      - name: Check integration-test status
+        run: |
+          RESULT="${{ needs.integration-test.result }}"
+          if [ "$RESULT" = "success" ] || [ "$RESULT" = "skipped" ]; then
+            exit 0
+          else
+            echo "integration-test failed with status: $RESULT"
+            exit 1
+          fi      
