Add arm64, ppc64el and s390x and migrate workflows to charm-ci (#99)

diff --git a/.github/workflows/integration_test.yaml b/.github/workflows/integration_test.yaml
--- a/.github/workflows/integration_test.yaml
+++ b/.github/workflows/integration_test.yaml
@@ -6,29 +6,31 @@ on:
     - cron: "0 15 * * SAT"
 
 jobs:
-  integration-tests:
-    strategy:
-      fail-fast: false
-      matrix:
-        base:
-          - "20.04"
-          - "22.04"
-          - "24.04"
-    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
+  integration-test:
+    uses: canonical/charm-ci/.github/workflows/integration-test.yml@main
     secrets: inherit
     permissions:
+      contents: read
       packages: write
+      actions: read
     with:
-      trivy-fs-enabled: true
-      trivy-image-config: "trivy.yaml"
-      self-hosted-runner: true
-      self-hosted-runner-label: "edge"
-      juju-channel: "3/stable"
-      provider: "lxd"
-      extra-arguments: "--base ${{ matrix.base }}"
-      with-uv: true
-  allure-report:
-    if: ${{ !cancelled() && github.event_name == 'schedule' }}
+      working-directory: .
+      spread-jobs-include: "*tests/integration*"
+      build-timeout-minutes: 120
+  required_status_checks:
+    name: Required Integration Test Status Checks
+    runs-on: ubuntu-latest
     needs:
-      - integration-tests
-    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
+      - integration-test
+    if: always() && !cancelled()
+    timeout-minutes: 5
+    steps:
+      - name: Check integration-test status
+        run: |
+          RESULT="${{ needs.integration-test.result }}"
+          if [ "$RESULT" = "success" ] || [ "$RESULT" = "skipped" ]; then
+            exit 0
+          else
+            echo "integration-test failed with status: $RESULT"
+            exit 1
+          fi
